import { NextRequest, NextResponse } from "next/server"
import JSZip from "jszip"
import { z } from "zod"

const schema = z.object({
  title: z.string().optional(),
  lyrics: z.string().optional(),
  stylePrompt: z.string().optional(),
  audioUrl: z.string().optional(),
  scenes: z.array(z.any()).optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
})

function generateCapCutGuide(title: string, sceneCount: number): string {
  return `# CapCut Editing Guide for "${title}"
Generated by MusicStudio AI

## Quick Start
1. Open CapCut and create a new project (1080x1920 for Shorts/TikTok or 1920x1080 for YouTube)
2. Import all images from this pack in order (scene-01 through scene-${String(sceneCount).padStart(2, "0")})
3. Add the audio file as background music
4. Set each image to auto-fit or fill the canvas

## Recommended Timeline
- Total scenes: ${sceneCount}
- Suggested display time per scene: adjust to match lyric sections
- Add transitions: fade or subtle crossfade between scenes

## Text Overlays
- Use lyrics.txt to add subtitles or karaoke-style text
- Font recommendation: Bold, high contrast with stroke/shadow
- Position: Bottom 20% of screen

## Export Settings
- Resolution: 1080p or 4K
- Frame rate: 30 FPS
- Format: MP4 H.264

## Tips
- Use CapCut's "Auto Captions" with lyrics.txt as reference
- Apply a light color grade to unify the visual style
- Add subtle background particles or blur for depth
- Use the style prompt from style-prompt.txt if you want to regenerate images

## Asset Files
- audio/: Contains the generated music files
- images/: Contains all scene images in order
- lyrics.txt: Full song lyrics with section markers
- style-prompt.txt: Suno-compatible style description
- scene-prompts.json: All image generation prompts for reference
- project-metadata.json: Full project details

Generated with ❤️ by MusicStudio AI
`
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const input = schema.parse(body)

    const zip = new JSZip()
    const title = input.title || "Untitled Song"
    const scenes = input.scenes || []

    // Create folder structure
    const audioFolder = zip.folder("audio")
    const imagesFolder = zip.folder("images")

    // Add lyrics
    if (input.lyrics) {
      zip.file("lyrics.txt", `${title}\n${"=".repeat(title.length)}\n\n${input.lyrics}`)
    }

    // Add style prompt
    if (input.stylePrompt) {
      zip.file(
        "style-prompt.txt",
        `SUNO STYLE PROMPT for "${title}"\n${"=".repeat(40)}\n\n${input.stylePrompt}\n\nCopy this into Suno's style prompt field when generating music.`
      )
    }

    // Add scene prompts JSON
    if (scenes.length > 0) {
      zip.file(
        "scene-prompts.json",
        JSON.stringify(
          scenes.map((s: { order?: number; lyricExcerpt?: string; prompt?: string; negativePrompt?: string; aspectRatio?: string }) => ({
            order: s.order,
            lyricExcerpt: s.lyricExcerpt,
            prompt: s.prompt,
            negativePrompt: s.negativePrompt,
            aspectRatio: s.aspectRatio,
          })),
          null,
          2
        )
      )
    }

    // Add metadata
    zip.file(
      "project-metadata.json",
      JSON.stringify(
        {
          title,
          generatedAt: new Date().toISOString(),
          sceneCount: scenes.length,
          ...input.metadata,
          generator: "MusicStudio AI",
          version: "1.0.0",
        },
        null,
        2
      )
    )

    // Add CapCut guide
    zip.file("capcut-guide.txt", generateCapCutGuide(title, scenes.length))

    // Add readme
    zip.file(
      "README.txt",
      `MusicStudio AI - Asset Pack for "${title}"\n\nSee capcut-guide.txt for editing instructions.\nOpen project-metadata.json for full project details.\n`
    )

    // Generate ZIP as base64 (in production, save to S3/storage)
    const zipBuffer = await zip.generateAsync({ type: "nodebuffer" })
    const base64 = zipBuffer.toString("base64")

    // In production, upload to S3 and return URL
    // For now, return as data URL (works for small packs)
    const dataUrl = `data:application/zip;base64,${base64}`

    return NextResponse.json({
      url: dataUrl,
      filename: `${title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}-pack.zip`,
      size: zipBuffer.length,
    })
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to create asset pack"
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
