"use client"

import { useState } from "react"
import {
  Package, Download, ChevronLeft, CheckCircle2,
  Music2, Image as ImageIcon, FileText, Loader2,
  Video, ArrowRight, FolderOpen, AlertCircle, X,
} from "lucide-react"
import JSZip from "jszip"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import type { ProjectData } from "./create-flow"

interface Props {
  data: Partial<ProjectData>
  onNext: () => void
  onBack: () => void
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function generateCapCutGuide(title: string, sceneCount: number): string {
  return `# CapCut Editing Guide for "${title}"
Generated by MusicStudio AI

## Quick Start
1. Open CapCut and create a new project (1080x1920 for Shorts/TikTok or 1920x1080 for YouTube)
2. Import all images from the images/ folder in order (scene-01 through scene-${String(sceneCount).padStart(2, "0")})
3. Add the audio file from audio/ as background music
4. Set each image to auto-fit or fill the canvas

## Recommended Timeline
- Total scenes: ${sceneCount}
- Suggested display time per scene: adjust to match lyric sections
- Add transitions: fade or subtle crossfade between scenes

## Text Overlays
- Use lyrics.txt to add subtitles or karaoke-style text
- Font recommendation: Bold, high contrast with stroke/shadow
- Position: Bottom 20% of screen

## Export Settings
- Resolution: 1080p or 4K
- Frame rate: 30 FPS
- Format: MP4 H.264

## Asset Files
- audio/: Generated music file(s)
- images/: Scene images in order
- lyrics.txt: Full song lyrics with section markers
- style-prompt.txt: Suno-compatible style description
- scene-prompts.json: All image generation prompts for reference
- project-metadata.json: Full project details

Generated with MusicStudio AI`
}

/** Try to fetch a URL and return ArrayBuffer. Returns null on failure. */
async function tryFetch(url: string): Promise<ArrayBuffer | null> {
  try {
    const res = await fetch(url, { mode: "cors" })
    if (!res.ok) return null
    return await res.arrayBuffer()
  } catch {
    // Try without CORS mode as fallback (works for same-origin + blob URLs)
    try {
      const res = await fetch(url)
      if (!res.ok) return null
      return await res.arrayBuffer()
    } catch {
      return null
    }
  }
}

function ext(url: string, fallback = "jpg"): string {
  const m = url.match(/\.(\w{2,4})(?:\?|$)/)
  return m ? m[1].toLowerCase() : fallback
}

// ── Main Component ────────────────────────────────────────────────────────────

export function Step6AssetPack({ data, onNext, onBack }: Props) {
  const [isBuilding, setIsBuilding] = useState(false)
  const [progress, setProgress] = useState(0)
  const [progressLabel, setProgressLabel] = useState("")
  const [failedFiles, setFailedFiles] = useState<string[]>([])
  const [done, setDone] = useState(false)

  const completedImages = data.scenes?.filter((s) => s.imageStatus === "completed" && s.imageUrl) || []
  const hasAudio = Boolean(data.audioUrl || data.importedAudioUrl)
  const hasLyrics = Boolean(data.lyrics)
  const title = data.title || "Untitled Song"
  const audioUrl = data.audioUrl || data.importedAudioUrl || ""

  const assetSummary = [
    { available: hasAudio,               label: "Audio track",                  icon: Music2 },
    { available: completedImages.length > 0, label: `${completedImages.length} scene images`, icon: ImageIcon },
    { available: hasLyrics,              label: "lyrics.txt",                   icon: FileText },
    { available: Boolean(data.stylePrompt), label: "style-prompt.txt",          icon: FileText },
    { available: Boolean(completedImages.length > 0), label: "scene-prompts.json", icon: FileText },
    { available: true,                   label: "capcut-guide.txt",             icon: Video },
  ]

  const totalSteps = 1 + (hasAudio ? 1 : 0) + completedImages.length
  let stepsDone = 0

  const tick = (label: string) => {
    stepsDone++
    setProgress(Math.round((stepsDone / totalSteps) * 100))
    setProgressLabel(label)
  }

  async function buildZip() {
    setIsBuilding(true)
    setProgress(0)
    setProgressLabel("Creating ZIP structure…")
    setFailedFiles([])
    const failed: string[] = []

    try {
      const zip = new JSZip()
      const audioFolder = zip.folder("audio")!
      const imagesFolder = zip.folder("images")!

      // ── Text files ──
      if (data.lyrics) {
        zip.file("lyrics.txt", `${title}\n${"=".repeat(title.length)}\n\n${data.lyrics}`)
      }
      if (data.stylePrompt) {
        zip.file(
          "style-prompt.txt",
          `SUNO STYLE PROMPT for "${title}"\n${"=".repeat(40)}\n\n${data.stylePrompt}\n\nCopy this into Suno's style prompt field when generating music.`
        )
      }
      if (data.scenes && data.scenes.length > 0) {
        zip.file(
          "scene-prompts.json",
          JSON.stringify(
            data.scenes.map((s) => ({
              order: s.order,
              lyricExcerpt: s.lyricExcerpt,
              prompt: s.prompt,
              negativePrompt: s.negativePrompt,
              aspectRatio: s.aspectRatio,
            })),
            null,
            2
          )
        )
      }
      zip.file(
        "project-metadata.json",
        JSON.stringify(
          {
            title,
            generatedAt: new Date().toISOString(),
            sceneCount: completedImages.length,
            genre: data.genre,
            mood: data.mood,
            audience: data.audience,
            generator: "MusicStudio AI",
            version: "1.0.0",
          },
          null,
          2
        )
      )
      zip.file("capcut-guide.txt", generateCapCutGuide(title, completedImages.length))
      zip.file(
        "README.txt",
        `MusicStudio AI – Asset Pack for "${title}"\n\nSee capcut-guide.txt for editing instructions.\nOpen project-metadata.json for full project details.\n`
      )

      tick("Text files added")

      // ── Audio ──
      if (audioUrl) {
        setProgressLabel("Downloading audio…")
        const buf = await tryFetch(audioUrl)
        if (buf) {
          const extension = ext(audioUrl, "mp3")
          audioFolder.file(`audio-01.${extension}`, buf)
          tick("Audio added")
        } else {
          failed.push(`audio/audio-01 (could not fetch)`)
          tick("Audio skipped — download it separately")
        }
      }

      // ── Images ──
      for (const scene of completedImages) {
        const idx = String(scene.order).padStart(2, "0")
        const filename = `scene-${idx}`
        setProgressLabel(`Downloading image ${scene.order} of ${completedImages.length}…`)

        const buf = scene.imageUrl ? await tryFetch(scene.imageUrl) : null
        if (buf) {
          const extension = ext(scene.imageUrl!, "jpg")
          imagesFolder.file(`${filename}.${extension}`, buf)
        } else {
          failed.push(`images/${filename} (could not fetch)`)
        }
        tick(`Image ${scene.order}`)
      }

      // ── Generate & trigger download ──
      setProgressLabel("Generating ZIP…")
      const blob = await zip.generateAsync(
        { type: "blob", compression: "DEFLATE", compressionOptions: { level: 6 } },
        (meta) => setProgress(Math.round(meta.percent))
      )

      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = `${title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}-pack.zip`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      setTimeout(() => URL.revokeObjectURL(url), 5000)

      setFailedFiles(failed)
      setDone(true)
      setProgress(100)
      setProgressLabel("Done!")

      if (failed.length > 0) {
        toast.warning(`ZIP downloaded — ${failed.length} file(s) skipped due to CORS restrictions.`)
      } else {
        toast.success("Asset pack downloaded!")
      }
    } catch (err) {
      console.error(err)
      toast.error("Failed to build ZIP. Try again.")
    } finally {
      setIsBuilding(false)
    }
  }

  return (
    <div className="space-y-6">
      {/* Asset checklist */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Package className="h-5 w-5 text-teal-400" />
            CapCut Asset Pack
          </CardTitle>
          <CardDescription>
            Download all your assets in one ZIP file, ready to import into CapCut
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
            {assetSummary.map((asset) => {
              const Icon = asset.icon
              return (
                <div
                  key={asset.label}
                  className={`flex items-center gap-2.5 p-2.5 rounded-lg ${
                    asset.available ? "bg-teal-500/5 border border-teal-500/20" : "bg-muted/40 border border-border/40"
                  }`}
                >
                  <div className={`w-6 h-6 rounded flex items-center justify-center shrink-0 ${asset.available ? "bg-teal-500/15" : "bg-muted"}`}>
                    {asset.available ? (
                      <CheckCircle2 className="h-4 w-4 text-teal-400" />
                    ) : (
                      <Icon className="h-4 w-4 text-muted-foreground opacity-40" />
                    )}
                  </div>
                  <span className={`text-xs ${asset.available ? "text-foreground" : "text-muted-foreground line-through"}`}>
                    {asset.label}
                  </span>
                </div>
              )
            })}
          </div>
        </CardContent>
      </Card>

      {/* ZIP structure preview */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-sm flex items-center gap-2">
            <FolderOpen className="h-4 w-4 text-muted-foreground" />
            ZIP Contents
          </CardTitle>
        </CardHeader>
        <CardContent className="font-mono text-xs text-muted-foreground space-y-0.5">
          <p className="text-foreground font-semibold">{title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}-pack.zip</p>
          <p>├── audio/</p>
          {hasAudio && <p className="pl-6 text-teal-400">└── audio-01.mp3</p>}
          {!hasAudio && <p className="pl-6 opacity-40">└── (empty — no audio generated)</p>}
          <p>├── images/</p>
          {completedImages.length > 0
            ? completedImages.slice(0, 3).map((s) => (
                <p key={s.order} className="pl-6 text-teal-400">
                  ├── scene-{String(s.order).padStart(2, "0")}.jpg
                </p>
              ))
            : <p className="pl-6 opacity-40">└── (empty — no images generated)</p>}
          {completedImages.length > 3 && (
            <p className="pl-6 text-muted-foreground">└── … +{completedImages.length - 3} more</p>
          )}
          <p>├── lyrics.txt</p>
          <p>├── style-prompt.txt</p>
          <p>├── scene-prompts.json</p>
          <p>├── capcut-guide.txt</p>
          <p>└── project-metadata.json</p>
        </CardContent>
      </Card>

      {/* CapCut guide */}
      <Card className="border-amber-500/20">
        <CardHeader className="pb-3">
          <CardTitle className="text-sm flex items-center gap-2">
            <Video className="h-4 w-4 text-amber-400" />
            How to use in CapCut
          </CardTitle>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground space-y-2">
          <ol className="list-decimal list-inside space-y-1">
            <li>Unzip the downloaded file</li>
            <li>Open CapCut → New project</li>
            <li>Import images from <code className="bg-secondary px-1 rounded">images/</code> in order</li>
            <li>Add <code className="bg-secondary px-1 rounded">audio/audio-01.mp3</code> as background music</li>
            <li>Adjust image duration to match lyric sections</li>
            <li>Add text overlays from <code className="bg-secondary px-1 rounded">lyrics.txt</code></li>
            <li>Export 1080p MP4 for best quality</li>
          </ol>
        </CardContent>
      </Card>

      {/* Download section */}
      <Card className={done ? "border-teal-500/30 bg-teal-500/5" : ""}>
        <CardContent className="p-5 space-y-4">
          {isBuilding && (
            <div className="space-y-2">
              <div className="flex items-center justify-between text-xs text-muted-foreground">
                <span>{progressLabel}</span>
                <span>{progress}%</span>
              </div>
              <Progress value={progress} className="h-2" />
            </div>
          )}

          {done && (
            <div className="flex items-center gap-3">
              <CheckCircle2 className="h-8 w-8 text-teal-400 shrink-0" />
              <div>
                <p className="font-semibold">Download started!</p>
                <p className="text-sm text-muted-foreground">
                  Check your Downloads folder for <code className="bg-secondary px-1 rounded text-xs">{title.replace(/[^a-z0-9]/gi, "-").toLowerCase()}-pack.zip</code>
                </p>
              </div>
            </div>
          )}

          {failedFiles.length > 0 && (
            <div className="rounded-lg border border-amber-500/20 bg-amber-500/5 p-3 space-y-1">
              <p className="text-xs font-medium text-amber-400 flex items-center gap-1.5">
                <AlertCircle className="w-3.5 h-3.5" />
                {failedFiles.length} file(s) skipped (CORS restriction)
              </p>
              {failedFiles.map((f) => (
                <p key={f} className="text-[10px] text-muted-foreground pl-5">{f}</p>
              ))}
              <p className="text-[10px] text-muted-foreground pl-5">
                Download these files individually from the steps above.
              </p>
            </div>
          )}

          <Button
            variant={done ? "outline" : "gradient"}
            size="lg"
            onClick={buildZip}
            disabled={isBuilding}
            className="w-full gap-2"
          >
            {isBuilding ? (
              <><Loader2 className="h-4 w-4 animate-spin" />{progressLabel || "Building…"}</>
            ) : done ? (
              <><Download className="h-4 w-4" />Download Again</>
            ) : (
              <><Package className="h-4 w-4" />Download Asset Pack ({completedImages.length} images{hasAudio ? " + audio" : ""})</>
            )}
          </Button>

          {!hasAudio && !done && (
            <p className="text-xs text-muted-foreground text-center">
              No audio generated yet — go back to Generate Music to create it.
            </p>
          )}
        </CardContent>
      </Card>

      {/* Action bar */}
      <div className="sticky bottom-0 -mx-4 md:-mx-6 lg:-mx-8 px-4 md:px-6 lg:px-8 py-4 bg-background/95 backdrop-blur border-t flex items-center justify-between gap-4">
        <Button variant="outline" onClick={onBack} className="gap-2">
          <ChevronLeft className="h-4 w-4" />
          Back
        </Button>
        <div className="flex items-center gap-3">
          <Button variant="outline" onClick={onNext} className="gap-2">
            Optional: Generate Video
            <ArrowRight className="h-4 w-4" />
          </Button>
          <Button variant="gradient" asChild>
            <a href="/projects">
              <FolderOpen className="h-4 w-4 mr-2" />
              View in Projects
            </a>
          </Button>
        </div>
      </div>
    </div>
  )
}
